version: '3'

services:
  db:
    container_name: siminc2-db
    image: culturagovbr/salic-db:latest
    ports:
      - 5432:5432
  web:
    image: culturagovbr/siminc2-web:1.0
    container_name: siminc2-web
    ports:
      - 8082:80 
      - 9002:9000
    volumes:
      - .:/var/www/siminc2
    environment:
      - APPLICATION_ENV=development
    depends_on:
      - db
