version: '3'

services:
  db:
    container_name: siminc2-db
    image: postgres:9.3
    volumes:
      - ./sql/restore/desenvolvimento.sh:/docker-entrypoint-initdb.d/desenvolvimento.sh
      - ./sql/restore/users.sql:/var/www/db-init/users.sql
      - ./sql/restore/siminc2_desenvolvimento.bkp:/var/www/db-init/siminc2_desenvolvimento.bkp
    ports:
      - 5452:5432
    restart: always
    environment: 
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: siminc2_desenvolvimento
    
  web:
    image: culturagovbr/siminc2
    container_name: siminc2
    ports:
      - 8082:80
      - 9002:9000
    volumes:
      - .:/var/www/siminc2
      - ./global/config-exemplo.inc:/var/www/siminc2/global/config.inc
      - ./global/database-exemplo.php:/var/www/siminc2/global/database.php
    environment:
      - APPLICATION_ENV=development
    depends_on:
      - db
