CREATE ROLE heronbonfim
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE ro_simec_c
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE ro_simec_t
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "simec-web"
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE siminc
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE simec LOGIN
  ENCRYPTED PASSWORD 'md59740e43bd91a1950814abdb18dc240ea'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT "simec-web" TO simec;

CREATE ROLE usr_simec LOGIN
  ENCRYPTED PASSWORD 'md58a424d10d8cadc12acf69f7d0fade84f'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

\l